server:
  port: 7800
spring:
  application:
    name: dm-base-consumer
  http:
    multipart:
      maxFileSize: 10Mb
    maxRequestSize:
      maxRequestSize: 10Mb
logging:
  level: debug
serverSavePath:
  /usr/local/images/